/*
 * Completion inside an inner class defined inside a labeled statement with a syntax error
 * just before the labeled statement.
 * TODO: excluded test (cannot get labels in recovery mode yet)
 */
public void _testInLabeledInnerClassWithErrorBefore() {
	this.runTestCheckMethodParse(
		// compilationUnit: 
		"class Bar {									\n" +
		"	void foo() {								\n" +
		"		int i == 2; \n" +
		"		label1: {								\n" +
		"			Object o = new Object() {			\n" +
		"				void fred() {					\n" +
		"					label2: {					\n" +
		"						X o = new Object();		\n" +
		"					}							\n" +
		"				}								\n" +
		"			};									\n" +
		"		}										\n" +
		"	}											\n" +
		"}												\n",
		// completeBehind:
		"X",
		// expectedCompletionNodeToString:
		"<CompleteOnName:X>",
		// expectedUnitDisplayString:
		"class Bar {\n" + 
		"  Bar() {\n" + 
		"  }\n" + 
		"  void foo() {\n" + 
		"    int i;\n" + 
		"    {\n" + 
		"      Object o;\n" + 
		"      new Object() {\n" + 
		"        () {\n" + 
		"        }\n" + 
		"        void fred() {\n" + 
		"          {\n" + 
		"            <CompleteOnName:X>;\n" + 
		"          }\n" + 
		"        }\n" + 
		"      };\n" + 
		"    }\n" + 
		"  }\n" + 
		"}\n",
		// expectedCompletionIdentifier:
		"X",
		// expectedReplacedSource:
		"X",
		// expectedLabels:
		new String[] {"label2"},
		// test name
		"<complete in labeled inner class with syntax error before>"
	);
}

