	void foo(){
		try{
		} catch(Ex e) {
		}
	}

